### ISSUE TITLE
What is the difference between `mod_channels` and `mod_channels_adjusted`?

### ISSUE THREAD

**Issue by DidierMalenfant** [Prezzodaman/pymod#15]
The code looks like it's changing between the two in a lot of place, as in:
```
mod_channel_pan = [0] * mod_channels_adjusted
```

which makes an array of `mod_channels_adjusted` values, but then:
```
for a in range(0, mod_channels):
    ...
    mod_channel_pan[a] = 0.5
```

which only goes over `mod_channels` values.

**Comment by Prezzodaman** [comment]
I've just done some testing, and it seems to be a holdover from older versions of Pymod! It originally existed because, when rendering modules with an odd number of channels, the waveform was offset (because the number of channels wasn't even). But I'm sure I fixed that issue, because I just replaced all instances of `mod_channels_adjusted` with `mod_channels` and all the tests passed!

Well spotted!
