### ISSUE TITLE
Merge code paths between single and multi channel output

### ISSUE THREAD

**Issue by DidierMalenfant** [Prezzodaman/pymod#4]
The code separates into two when dealing with rendering a single channel and rendering a mix of all channels.

That's probably a bit error-prone, especially ones that could only take place in one codepath and not the other.

Any issue with changing this and making code always act like it's a mix of channels but just mute other channels when rendering only one?

I can provide a PR for this.

**Comment by Prezzodaman** [comment]
Are you referring to the way channel bytes are stored (as either left/right, or a mixed byte)? The code *used to* store all channels at once when rendering individually, but that was a problem (especially on my laptop) as I found myself running out of RAM very quickly, as all channels were stored as once. That's why when rendering a mix, all channels are added to a single byte, and when rendering individually, each channel is done one at a time. It's a lot slower, but it saves lots of RAM.

That being said, if you can think of a better way (and I'm sure there is), I'd love to hear it!

**Comment by DidierMalenfant** [comment]
This was taken care of by #13
